# Generated by Django 3.0.3 on 2020-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('interface', models.CharField(max_length=100)),
                ('ram_in_mb', models.PositiveSmallIntegerField()),
                ('cpu', models.PositiveSmallIntegerField()),
                ('host', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('profile', 'name'),
                'unique_together': {('name', 'profile')},
            },
        ),
    ]
