# Generated by Django 3.1.7 on 2021-06-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interface', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('ram_in_mb', models.PositiveSmallIntegerField()),
                ('cpu', models.PositiveSmallIntegerField()),
                ('role', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('extra_storage_in_gb', models.PositiveSmallIntegerField(default=1)),
                ('extra_storage_pool', models.CharField(choices=[('default', 'default'), ('storage', 'storage'), ('ramdisk', 'ramdisk')], default='default', max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.hypervisor')),
            ],
            options={
                'ordering': ('profile', 'name'),
                'unique_together': {('name', 'profile')},
            },
        ),
    ]
