# Generated by Django 3.1.7 on 2022-02-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_virtualmachine_static_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='saltmaster_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
