# Generated by Django 3.1.7 on 2022-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_virtualmachine_saltmaster_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='ipv6_overlay',
            field=models.BooleanField(default=True),
        ),
    ]
