# Generated by Django 3.1.7 on 2022-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20220312_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
