# Generated by Django 3.1.7 on 2022-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20220312_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='network_interface_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
