# Generated by Django 3.2.20 on 2023-07-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_virtualmachine_network_interface_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='ipv6_ip',
        ),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='ipv6_overlay',
        ),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='ipv6_privkey',
        ),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='ipv6_pubkey',
        ),
    ]
